ALLOWED_TONES = {
    "casual",
    "polite",
    "formal",
    "flirty",
    "professional",
    "witty",
    "direct",
    "friendly",
    "empathetic",
    "confident",
}

SAFETY_BLOCK_PATTERNS = [
    "blackmail",
    "extort",
    "threaten",
    "stalk",
    "doxx",
    "revenge porn",
    "force them",
    "manipulate",
    "gaslight",
    "make her jealous",
    "make him jealous",
    "underage sex",
    "minor sex",
    "sexual minor",
    "pressure them",
    "coerce",
    "humiliate",
    "degrade them",
    "control them",
    "obsess over",
    "won't take no",
    "won't accept no",
    "lie to them",
    "catfish",
    "trick them",
    "cheat on",
    "hide that i'm",
]
