import re

CANONICAL_SKILLS = [
    "Communication",
    "Problem Solving",
    "React",
    "Node.js",
    "JavaScript",
    "TypeScript",
    "Next.js",
    "MongoDB",
    "PostgreSQL",
    "Express.js",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "Figma",
    "UI Design",
    "UX Design",
    "UI/UX Design",
    "Python",
    "Java",
    "C++",
    "Prisma",
    "Redis",
    "Socket.IO",
    "AWS",
    "Docker",
    "Git",
    "Go",
    "Kubernetes",
    "GraphQL",
    "FastAPI",
    "CI/CD",
    "Linux",
    "REST APIs",
    "Microservices",
    "System Design",
    "DevOps",
    "Data Analysis",
    "SQL",
    "Firebase",
    "React Native",
]

SKILL_ALIASES = {
    "reactjs": "React",
    "react js": "React",
    "react": "React",
    "node": "Node.js",
    "nodejs": "Node.js",
    "node js": "Node.js",
    "javascript": "JavaScript",
    "js": "JavaScript",
    "typescript": "TypeScript",
    "ts": "TypeScript",
    "nextjs": "Next.js",
    "next js": "Next.js",
    "mongodb": "MongoDB",
    "mongo db": "MongoDB",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "expressjs": "Express.js",
    "express js": "Express.js",
    "html": "HTML",
    "css": "CSS",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "figma": "Figma",
    "ui ux": "UI/UX Design",
    "ui/ux": "UI/UX Design",
    "ux": "UX Design",
    "ui": "UI Design",
    "python": "Python",
    "java": "Java",
    "c++": "C++",
    "prisma": "Prisma",
    "redis": "Redis",
    "socketio": "Socket.IO",
    "socket.io": "Socket.IO",
    "aws": "AWS",
    "docker": "Docker",
    "git": "Git",
    "golang": "Go",
    "go": "Go",
    "k8s": "Kubernetes",
    "kubernetes": "Kubernetes",
    "graphql": "GraphQL",
    "fast api": "FastAPI",
    "fastapi": "FastAPI",
    "ci cd": "CI/CD",
    "cicd": "CI/CD",
    "linux": "Linux",
    "rest api": "REST APIs",
    "rest apis": "REST APIs",
    "api design": "REST APIs",
    "microservices": "Microservices",
    "system design": "System Design",
    "devops": "DevOps",
    "data analysis": "Data Analysis",
    "sql": "SQL",
    "firebase": "Firebase",
    "react native": "React Native",
}

CANONICAL_SKILL_LOOKUP = {skill.lower(): skill for skill in CANONICAL_SKILLS}

KNOWN_COMPANY_STOPWORDS = {
    "React",
    "Node",
    "Node.js",
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "Docker",
    "AWS",
    "CliQ",
}

CERTIFICATION_PATTERNS = [
    re.compile(r"\bAWS Certified [A-Za-z0-9 .-]+\b", re.IGNORECASE),
    re.compile(r"\bGoogle Cloud Certified [A-Za-z0-9 .-]+\b", re.IGNORECASE),
    re.compile(r"\bMicrosoft Certified: [A-Za-z0-9 .-]+\b", re.IGNORECASE),
    re.compile(r"\bAzure (?:Administrator|Developer|Solutions Architect|Data Engineer)[A-Za-z0-9 .-]*\b", re.IGNORECASE),
    re.compile(r"\bCertified Kubernetes (?:Administrator|Application Developer|Security Specialist)\b", re.IGNORECASE),
    re.compile(r"\b(?:PMP|CSM|PSM I|PSM II|CKA|CKAD|CKS|RHCSA|RHCE)\b", re.IGNORECASE),
    re.compile(r"\b[A-Za-z0-9 .-]+ certification\b", re.IGNORECASE),
]

TITLE_PATTERNS = [
    (("frontend", "front end"), "Frontend Developer"),
    (("backend", "back end"), "Backend Developer"),
    (("full stack", "fullstack"), "Full Stack Developer"),
    (("product designer",), "Product Designer"),
    (("ui/ux", "ui ux", "ux designer"), "UI/UX Designer"),
    (("software engineer",), "Software Engineer"),
    (("developer",), "Software Developer"),
    (("data analyst",), "Data Analyst"),
    (("data scientist",), "Data Scientist"),
    (("devops",), "DevOps Engineer"),
]
